/**
 * The wire contract between the front end and the Rust backend.
 *
 * The types themselves are GENERATED from the Rust structs in
 * `server/src/protocol.rs` by `ts-rs`, and land in `./generated/`. They are
 * regenerated by `cargo test -p server`, so if the Rust and the TypeScript
 * drift, the build breaks rather than the game.
 *
 * Do not hand-edit anything in `./generated/`. This file re-exports those types
 * and adds the helpers that have no Rust equivalent.
 *
 * Two conventions worth knowing, both enforced on the Rust side:
 *  - Every field is camelCase on the wire.
 *  - Events and commands are discriminated unions tagged on `t`.
 *
 * Note on sizes: every order is one lot, so a trade always fully consumes
 * exactly one resting order. There are no partial fills in this protocol.
 */

export type { BookState } from "./generated/BookState";
export type { ClientCommand } from "./generated/ClientCommand";
export type { CreateSessionRequest } from "./generated/CreateSessionRequest";
export type { CreateSessionResponse } from "./generated/CreateSessionResponse";
export type { Direction } from "./generated/Direction";
export type { JoinSessionRequest } from "./generated/JoinSessionRequest";
export type { JoinSessionResponse } from "./generated/JoinSessionResponse";
export type { Order } from "./generated/Order";
export type { Phase } from "./generated/Phase";
export type { Player } from "./generated/Player";
export type { RejectReason } from "./generated/RejectReason";
export type { Result } from "./generated/Result";
export type { ServerEvent } from "./generated/ServerEvent";
export type { SessionMeta } from "./generated/SessionMeta";
export type { Settlement } from "./generated/Settlement";
export type { Side } from "./generated/Side";
export type { Trade } from "./generated/Trade";
export type { YouState } from "./generated/YouState";

import type { BookState } from "./generated/BookState";
import type { Order } from "./generated/Order";
import type { Trade } from "./generated/Trade";

/* ------------------------------------------------------------------ */
/* Helpers                                                             */
/* ------------------------------------------------------------------ */

export const bestBid = (book: BookState): Order | undefined => book.bids[0];
export const bestOffer = (book: BookState): Order | undefined => book.offers[0];

export function spread(book: BookState): number | null {
  const b = bestBid(book);
  const o = bestOffer(book);
  return b && o ? o.price - b.price : null;
}

/** Position is derivable from the public tape, since trades carry names. */
export function positionFrom(trades: Trade[], playerId: string): number {
  let pos = 0;
  for (const tr of trades) {
    if (tr.buyerId === playerId) pos += 1;
    if (tr.sellerId === playerId) pos -= 1;
  }
  return pos;
}

export function tradesInvolving(trades: Trade[], playerId: string): Trade[] {
  return trades.filter((t) => t.buyerId === playerId || t.sellerId === playerId);
}

export function formatPrice(price: number, tickSize: number | null): string {
  if (tickSize && tickSize < 1) {
    const dp = Math.min(6, (String(tickSize).split(".")[1] ?? "").length);
    return price.toFixed(dp);
  }
  return Number.isInteger(price) ? String(price) : String(Number(price.toFixed(4)));
}
